version: 0.2

phases:
  install:
    commands:
      - wget https://github.com/gohugoio/hugo/releases/download/v0.75.1/hugo_0.75.1_Linux-64bit.tar.gz
      - tar zxvf ./hugo_0.75.1_Linux-64bit.tar.gz
  build:
    commands:
      - rm -fr public
      - mkdir public
      - git clone https://github.com/mrmikemarshall/mrmikemarshall.github.io.git public
      - ./hugo -t ananke
      