version: 0.2

phases:
  pre-build:
    commands:
      - wget https://github.com/gohugoio/hugo/releases/download/v0.75.1/hugo_0.75.1_Linux-64bit.tar.gz
      - tar zxvf ./hugo_0.75.1_Linux-64bit.tar.gz
      - export PATH=$PATH:./hugo_0.75.1_Linux-64bit
  build:
    commands:
      - hugo_0.75.1_Linux-64bit -t ananke
  post_build:
    commands:
      - git add *
      - git commit -m "codebuild"
      - git push
      