version: 0.2

phases:
  install:
    commands:
      - wget https://github.com/gohugoio/hugo/releases/download/v0.75.1/hugo_0.75.1_Linux-64bit.tar.gz
      - tar zxvf ./hugo_0.75.1_Linux-64bit.tar.gz
  build:
    commands:
      - echo "$(pwd)"
      - env
      - ./hugo -t ananke
      - cd public
      - git add .
      - git config user.name "Mike Marshall"
      - git config user.email "mrmikemarshall@gmail.com"
      - git commit -m "${CODEBUILD_BUILD_ID}"
      - git push origin master
      