version: 0.2

phases:
  
  build:
    commands:
      - docker run --rm -it -v $(pwd):/src klakegg/hugo:0.74.3-alpine "-t ananke"
  post_build:
    commands:
      - git add *
      - git commit -m "codebuild"
      - git push
      